version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./docker/db/mysql_env_variable.env
